### ISSUE TITLE
FireHOL: Explicitly specify interface “priority” or “order”?

### ISSUE THREAD

**Issue by haasn** [firehol/firehol#174]
With FireQoS, it's possible to specify the classes in any order and manually assign their priority with “prio”.

It would be interesting if I could do that with FireHOL as well, so I can explicitly mark my “fallback” interface with a low priority and have it apply as the last interface, regardless of what order I specify the interfaces in.

The motivation here is to make it easier to generate FireHOL rules using something like ansible or puppet templating - right now, I have a set of “common” rules that apply to all hosts, and a set of host-specific rules that only apply to that host. I would like to include the “interface any world { server icmp accept; client all accept; policy reject }” in my ‘common’ rules, but I need it to apply *after* any host-specific rules (which all end with ‘policy return’).

Since it's more difficult to control the exact order in which rules are templated into the file than it is to simply associate a low priority with the rules I know need to apply after other rules, this feature would be a quality of life improvement.

**Comment by ktsaou** [comment]
hm... this seems pretty easy to do it yourself...

Let's see:

1. Create the directory `/etc/firehol/rules.d`.
2. Put in it files with names `NN-name.conf`, where `NN` is a number, giving the order of processing.
3. Put this as `/etc/firehol/firehol.conf`:

```sh
for file in $(ls /etc/firehol/rules.d/*.conf | sort -n)
do
    source $file
done
```

In general, since the configuration of these files are bash scripts, you can do whatever imaginable, pretty easily. You can follow this rule for both firehol and fireqos (using different directories of course).

**Comment by haasn** [comment]
Oh, that's an interesting way of approaching things.
