### ISSUE TITLE
travis failing

### ISSUE THREAD

**Issue by ktsaou** [firehol/firehol#181]
@philwhineray have a look at this: https://travis-ci.org/firehol/firehol/builds/188969359

Did I do something wrong?

**Comment by philwhineray** [comment]
Interesting. No I think this looks like a problem with the Travis setup
itself. Not sure why it is only showing a problem now though, since it
hasn't changed.

I should be able to fix it without too much bother, I think. I'll take a
quick look later when I have something better than a phone to work with!

**Comment by philwhineray** [comment]
OK I pushed a fix which seems to have done the job.
