### ISSUE TITLE
 ip6tables v1.4.14: host/network not found

### ISSUE THREAD

**Issue by Alekc** [firehol/firehol#202]
Ok, this is weird: recently I've upgraded my firehol installation from standard jessie release to the last stable, and some of my rules are not working anymore. One bug in particular is leaving me speechless, was there some syntax change in latest version? 

I am trying to apply folllowing configuration:
```
#!/sbin/firehol
# : firehol.sh,v 1.273 2008/07/31 00:46:41 ktsaou Exp $
#

interface venet0 wan

        # The default policy is DROP. You can be more polite with REJECT.
        # Prefer to be polite on your own clients to prevent timeouts.
        policy drop

        # Here are the services listening on venet0.
        # TODO: Normally, you will have to remove those not needed.
        server http accept
        server ICMP accept
        server ssh accept

        # The following venet0 services are not known by FireHOL:
        # tcp/5005 tcp/9009 udp/49352

        #office
        server all accept src 163.172.15.111

        client all accept
```

and this configuration fails with following errors:

```
ERROR   : # 1.
WHAT    : A runtime command failed to execute (returned error 2).
SOURCE  : 38@/etc/firehol/firehol.conf: server:
COMMAND : /sbin/ip6tables -t filter -A in_wan -s 163.172.15.111 -m conntrack --ctstate NEW\,ESTABLISHED -j ACCEPT
OUTPUT  :

ip6tables v1.4.14: host/network `163.172.15.111' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.

```

I tried to change ip, adding /32 but no luck. Am I missing something obvious here?

**Comment by ktsaou** [comment]
The problem is that you have an ipv4 IP address in a rule that is applied to both ipv4 and ipv6.

You have several options:

1. Apply the whole firewall only to ipv4 - edit `/etc/firehol/firehol-defaults.conf` and set `ENABLE_IPV6=0`.
2. Turn the whole `interface` and all its rules to ipv4 - change the `interface venet0 ...` to `ipv4 interface venet0 ...` or `interface4 venet0 ...`.
3. Leave the interface matching both ipv4 and ipv6, but change only the `server all accept ...` rule to ipv4 -  change it to `ipv4 server all accept ... ` or `server4 all accept ...`.

**Comment by Alekc** [comment]
Ok, great thanks. I think 3d option probably would be the best one since I am beginning to see ipv6 src hitting my services.
