### ISSUE TITLE
How to prevent temporary ALLOW ALL state during firehol restart?

### ISSUE THREAD

**Issue by nodiscc** [firehol/firehol#397]
Hi, during FireHOL restart operations, iptables rules are cleared and the machine temporarily has ACCEPT ALL policy for INPUT, OUTPUT, FORWARD chains.

```
$ sudo systemctl restart firehol
FireHOL[23786]: Firewall has been stopped. Policy is ACCEPT EVERYTHING!
```

How would I prevent this? For example I would like to define a fallback policy in case the firewall is off, only allowing SSH (tcp/22) on INPUT, and dropping everything else.

How can I achieve this?

**Comment by philwhineray** [comment]
If you just run `firehol start` (even if it is already running) rather than going through systemd or any other init system it should replace the firewall in-situ and not disrupt connections that are permitted both before and after.

If you are changing rules you might want to use `firehol try` since there is no exemption for ssh.

A fallback policy when no firewall is running is not something that is really meaningful (since it's just another firewall config) but you could probably customise the init system to load a basic set of rules very early on by using iptables-save and restore.

**Comment by leoluk** [comment]
Most distros have an `ExecStop` setting in their systemd service files for firehol. This causes the firewall to be disabled on `restart` as well as during reboot/shutdown. I always override ExecStop= on my hosts to prevent this.

**Comment by nodiscc** [comment]
> I always override ExecStop= on my hosts to prevent this.

@leoluk but then you can't `systemctl stop firehol` at all?

**Comment by leoluk** [comment]
Yes, I don't want systemd to ever stop firehol.

It's still possible to run `firehol stop`

**Comment by nodiscc** [comment]
`ExecReload=/usr/sbin/firehol start` is now implemented in the systemd service file (https://github.com/firehol/firehol/blob/master/contrib/firehol.service), which allows updating firehol rules using systemctl without clearing them, effectively preventing the `Policy is ACCEPT EVERYTHING!` situation.

Thanks!
