### ISSUE TITLE
IP blacklisted 163.172.0.0/16

### ISSUE THREAD

**Issue by arnausc** [firehol/firehol#470]
This range belongs to online.net and I have a bunch of servers, a /27, inside this range. As a matter of fact, it belonged to me for the last two years.
I don't know how to proceed.

Thanks

**Comment by philwhineray** [comment]
Hi

The firehol lists are just an aggregate of other publically available lists. We don't actively manage these sources.

You really need to identify the source lists that your IPs have been added  to and deal with their admins. Once they are removed from those they will be removed from the firehol lists automatically and you will also have unblocked them for anyone using those lists directly.

The source lists for each firehol list is included on the site http://iplists.firehol.org/ and you can also clone the repo https://github.com/firehol/blocklist-ipsets.git in order to search for which lists contain the relevant IP address or range.

Hope that helps

Kind regards
Phil
