### ISSUE TITLE
Is firehol EOL or just stable?

### ISSUE THREAD

**Issue by wsw70** [firehol/firehol#481]
I was considering moving to firehol with a new router I will configure from scratch but I see a lot of issues open, a few pending PRs and 3 commits for a year.

Is this a hint that it is more or less abandoned, or just super stable and evolutions are not needed?

**Comment by philwhineray** [comment]
Mostly it's super stable, but I for one don't have any real time to devote for further development.

If people step up to review the code submissions and fix bugs etc. there is surely more that can be done but I suspect one of the reasons so little happens is it mostly just works.

If I had one concern then it would be the possibility that iptables compatibility is removed from the kernel. That would generate a lot of work but it seems unlikely that will happen any time soon, if at all.

Until I hear such a change is likely I will continue to use Firehol myself on routers, since all we're really doing is generating iptables rules, and all my use cases are covered.

If it does come about I'll be weighing the effort of changing firewall frontend vs the cost of implementing an nftables backend to firehol.

**Comment by wsw70** [comment]
Thank you @philwhineray for the comprehensive answer.

I am planning to switch from a Ubiquity router at home (which already replaced the crappy ISP-provided router) to a small PC that will manage the firewall (and a few other services). It will be Debian so the full mighty-ness of `iptables` is on the road. I have administered Linux machines for 30 years but never went into the details of `iptables` and Firehole (or Shorewall) are real-life savers, thank you.

**One last concern**: would you say that the community around Firehole is active enough to help someone who is reasonably experienced with networking but would have some questions on the way (I am mostly thinking about reactivity - I wrote and use opensource so I am completely aware of the reality of supporting such software - so this is really to just probing the "risk" of being mostly alone around a new product)

**Comment by philwhineray** [comment]
Fair question. I apologise but I don't really know - things are pretty quiet but not totally silent, so your mileage may vary.

Given your requirements seem simple you should probably be fine but I can't make promises, obviously.

**Comment by wsw70** [comment]
Thanks for the follow-up
